=begin
 
----------- Problem 2 ------------
 
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 find the sum of the even-valued terms.
  
=end

# totals the fibonacci sequence up to a given value
# (not the nth fibonacci value, the real value)

def fibonacci_sum(maximum_value)
  sum = 2
  a = 1; b = 2; next_value = 0
  while (a + b < maximum_value)
    next_value = a + b
    sum += next_value if next_value % 2 == 0 # if even
    a = b
    b = next_value
  end
  return sum
end

# answer to problem

puts fibonacci_sum(4_000_000)

# => 4613732

